/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as MoscriptRouteImport } from './routes/moscript'
import { Route as MindgraphRouteImport } from './routes/mindgraph'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CouncilRouteImport } from './routes/council'
import { Route as ContinentOpticsRouteImport } from './routes/continent-optics'
import { Route as ConduitRouteImport } from './routes/conduit'
import { Route as BootRouteImport } from './routes/boot'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const MoscriptRoute = MoscriptRouteImport.update({
  id: '/moscript',
  path: '/moscript',
  getParentRoute: () => rootRouteImport,
} as any)
const MindgraphRoute = MindgraphRouteImport.update({
  id: '/mindgraph',
  path: '/mindgraph',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilRoute = CouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinentOpticsRoute = ContinentOpticsRouteImport.update({
  id: '/continent-optics',
  path: '/continent-optics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConduitRoute = ConduitRouteImport.update({
  id: '/conduit',
  path: '/conduit',
  getParentRoute: () => rootRouteImport,
} as any)
const BootRoute = BootRouteImport.update({
  id: '/boot',
  path: '/boot',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/boot': typeof BootRoute
  '/conduit': typeof ConduitRoute
  '/continent-optics': typeof ContinentOpticsRoute
  '/council': typeof CouncilRoute
  '/events': typeof EventsRoute
  '/memory': typeof MemoryRoute
  '/mindgraph': typeof MindgraphRoute
  '/moscript': typeof MoscriptRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/boot': typeof BootRoute
  '/conduit': typeof ConduitRoute
  '/continent-optics': typeof ContinentOpticsRoute
  '/council': typeof CouncilRoute
  '/events': typeof EventsRoute
  '/memory': typeof MemoryRoute
  '/mindgraph': typeof MindgraphRoute
  '/moscript': typeof MoscriptRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/boot': typeof BootRoute
  '/conduit': typeof ConduitRoute
  '/continent-optics': typeof ContinentOpticsRoute
  '/council': typeof CouncilRoute
  '/events': typeof EventsRoute
  '/memory': typeof MemoryRoute
  '/mindgraph': typeof MindgraphRoute
  '/moscript': typeof MoscriptRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/boot'
    | '/conduit'
    | '/continent-optics'
    | '/council'
    | '/events'
    | '/memory'
    | '/mindgraph'
    | '/moscript'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/boot'
    | '/conduit'
    | '/continent-optics'
    | '/council'
    | '/events'
    | '/memory'
    | '/mindgraph'
    | '/moscript'
    | '/voice'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/boot'
    | '/conduit'
    | '/continent-optics'
    | '/council'
    | '/events'
    | '/memory'
    | '/mindgraph'
    | '/moscript'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BootRoute: typeof BootRoute
  ConduitRoute: typeof ConduitRoute
  ContinentOpticsRoute: typeof ContinentOpticsRoute
  CouncilRoute: typeof CouncilRoute
  EventsRoute: typeof EventsRoute
  MemoryRoute: typeof MemoryRoute
  MindgraphRoute: typeof MindgraphRoute
  MoscriptRoute: typeof MoscriptRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moscript': {
      id: '/moscript'
      path: '/moscript'
      fullPath: '/moscript'
      preLoaderRoute: typeof MoscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindgraph': {
      id: '/mindgraph'
      path: '/mindgraph'
      fullPath: '/mindgraph'
      preLoaderRoute: typeof MindgraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council': {
      id: '/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof CouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continent-optics': {
      id: '/continent-optics'
      path: '/continent-optics'
      fullPath: '/continent-optics'
      preLoaderRoute: typeof ContinentOpticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conduit': {
      id: '/conduit'
      path: '/conduit'
      fullPath: '/conduit'
      preLoaderRoute: typeof ConduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boot': {
      id: '/boot'
      path: '/boot'
      fullPath: '/boot'
      preLoaderRoute: typeof BootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BootRoute: BootRoute,
  ConduitRoute: ConduitRoute,
  ContinentOpticsRoute: ContinentOpticsRoute,
  CouncilRoute: CouncilRoute,
  EventsRoute: EventsRoute,
  MemoryRoute: MemoryRoute,
  MindgraphRoute: MindgraphRoute,
  MoscriptRoute: MoscriptRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
