/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWatchtowerRouteImport } from './routes/dashboard.watchtower'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSanctuaryRouteImport } from './routes/dashboard.sanctuary'
import { Route as DashboardMoscriptsRouteImport } from './routes/dashboard.moscripts'
import { Route as DashboardMindGraphRouteImport } from './routes/dashboard.mind-graph'
import { Route as DashboardCouncilRouteImport } from './routes/dashboard.council'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWatchtowerRoute = DashboardWatchtowerRouteImport.update({
  id: '/watchtower',
  path: '/watchtower',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSanctuaryRoute = DashboardSanctuaryRouteImport.update({
  id: '/sanctuary',
  path: '/sanctuary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMoscriptsRoute = DashboardMoscriptsRouteImport.update({
  id: '/moscripts',
  path: '/moscripts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMindGraphRoute = DashboardMindGraphRouteImport.update({
  id: '/mind-graph',
  path: '/mind-graph',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCouncilRoute = DashboardCouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/council': typeof DashboardCouncilRoute
  '/dashboard/mind-graph': typeof DashboardMindGraphRoute
  '/dashboard/moscripts': typeof DashboardMoscriptsRoute
  '/dashboard/sanctuary': typeof DashboardSanctuaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/watchtower': typeof DashboardWatchtowerRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/council': typeof DashboardCouncilRoute
  '/dashboard/mind-graph': typeof DashboardMindGraphRoute
  '/dashboard/moscripts': typeof DashboardMoscriptsRoute
  '/dashboard/sanctuary': typeof DashboardSanctuaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/watchtower': typeof DashboardWatchtowerRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/council': typeof DashboardCouncilRoute
  '/dashboard/mind-graph': typeof DashboardMindGraphRoute
  '/dashboard/moscripts': typeof DashboardMoscriptsRoute
  '/dashboard/sanctuary': typeof DashboardSanctuaryRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/watchtower': typeof DashboardWatchtowerRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/council'
    | '/dashboard/mind-graph'
    | '/dashboard/moscripts'
    | '/dashboard/sanctuary'
    | '/dashboard/settings'
    | '/dashboard/watchtower'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/council'
    | '/dashboard/mind-graph'
    | '/dashboard/moscripts'
    | '/dashboard/sanctuary'
    | '/dashboard/settings'
    | '/dashboard/watchtower'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/council'
    | '/dashboard/mind-graph'
    | '/dashboard/moscripts'
    | '/dashboard/sanctuary'
    | '/dashboard/settings'
    | '/dashboard/watchtower'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/watchtower': {
      id: '/dashboard/watchtower'
      path: '/watchtower'
      fullPath: '/dashboard/watchtower'
      preLoaderRoute: typeof DashboardWatchtowerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sanctuary': {
      id: '/dashboard/sanctuary'
      path: '/sanctuary'
      fullPath: '/dashboard/sanctuary'
      preLoaderRoute: typeof DashboardSanctuaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/moscripts': {
      id: '/dashboard/moscripts'
      path: '/moscripts'
      fullPath: '/dashboard/moscripts'
      preLoaderRoute: typeof DashboardMoscriptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mind-graph': {
      id: '/dashboard/mind-graph'
      path: '/mind-graph'
      fullPath: '/dashboard/mind-graph'
      preLoaderRoute: typeof DashboardMindGraphRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/council': {
      id: '/dashboard/council'
      path: '/council'
      fullPath: '/dashboard/council'
      preLoaderRoute: typeof DashboardCouncilRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCouncilRoute: typeof DashboardCouncilRoute
  DashboardMindGraphRoute: typeof DashboardMindGraphRoute
  DashboardMoscriptsRoute: typeof DashboardMoscriptsRoute
  DashboardSanctuaryRoute: typeof DashboardSanctuaryRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWatchtowerRoute: typeof DashboardWatchtowerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCouncilRoute: DashboardCouncilRoute,
  DashboardMindGraphRoute: DashboardMindGraphRoute,
  DashboardMoscriptsRoute: DashboardMoscriptsRoute,
  DashboardSanctuaryRoute: DashboardSanctuaryRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWatchtowerRoute: DashboardWatchtowerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
