import asyncio
import logging
import feedparser
from grid.events import event_bus, GridEvent

logger = logging.getLogger("grid_watchers")

class MoodEngine:
    def __init__(self):
        self.current_mood = "stable"
        self.recent_events = []

    def observe(self, event: GridEvent):
        self.recent_events.append(event)
        if len(self.recent_events) > 10:
            self.recent_events.pop(0)
            
        # Very simple mood calculation based on recent severities
        high_critical = sum(1 for e in self.recent_events if e.severity in ["high", "critical"])
        
        if high_critical >= 2:
            self.current_mood = "critical"
        elif high_critical == 1:
            self.current_mood = "alert"
        else:
            self.current_mood = "stable"
            
        return self.current_mood

mood_engine = MoodEngine()

async def world_signal_watcher():
    """Polls RSS feeds for high severity events periodically."""
    logger.info("WorldSignalWatcher started.")
    last_top_headline = ""
    
    while True:
        try:
            africa_feed = feedparser.parse("https://feeds.bbci.co.uk/news/world/africa/rss.xml")
            if africa_feed.entries:
                top_entry = africa_feed.entries[0]
                headline = top_entry.title
                
                # Check if it's new
                if headline != last_top_headline:
                    last_top_headline = headline
                    
                    # Naive severity detection: words indicating crisis
                    crisis_words = ["flood", "war", "crisis", "attack", "death", "crash", "emergency"]
                    severity = "low"
                    if any(w in headline.lower() for w in crisis_words):
                        severity = "high"
                        
                    event = GridEvent(
                        type="world_signal",
                        severity=severity,
                        mood=mood_engine.current_mood, # will be updated on next observe
                        source="world_signal_watcher",
                        text=headline,
                        payload={"url": top_entry.link}
                    )
                    
                    mood = mood_engine.observe(event)
                    event.mood = mood # update with new mood
                    
                    await event_bus.publish(event)
                    
        except Exception as e:
            logger.error(f"WorldSignalWatcher error: {e}")
            
        # Poll every 5 minutes
        await asyncio.sleep(300)

async def telemetry_watcher(orchestrator):
    """Polls grid telemetry for anomalies."""
    logger.info("TelemetryWatcher started.")
    last_pulse = 100.0
    
    while True:
        try:
            # Let's say we have access to orchestrator status
            status = await orchestrator.status()
            
            # Simulated pulse drop check for demonstration. 
            # In reality, pulse is generated by ClusterTelemetry.
            # We'll just look at mindgraph connection status
            mindgraph_ok = status.get("mindgraph", {}).get("connected", False)
            
            severity = "low"
            text = "Telemetry stable"
            
            if not mindgraph_ok:
                severity = "critical"
                text = "MindGraph connection lost!"
                
                event = GridEvent(
                    type="telemetry_alert",
                    severity=severity,
                    mood=mood_engine.current_mood,
                    source="telemetry_watcher",
                    text=text,
                    payload={"status": status}
                )
                
                mood = mood_engine.observe(event)
                event.mood = mood
                
                await event_bus.publish(event)
                
        except Exception as e:
            logger.error(f"TelemetryWatcher error: {e}")
            
        # Poll every 30 seconds
        await asyncio.sleep(30)
