#!/usr/bin/env python3
"""Fail-closed, model-agnostic census and evidence ledger for inference surfaces."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKIP_DIRS = {
    ".git": "repository metadata",
    ".venv": "third-party environment",
    "node_modules": "vendored dependencies",
    "__pycache__": "generated bytecode",
    ".tmp": "temporary artifacts",
    "logs": "runtime output, not source",
    "data": "runtime data, not executable source",
    "mindgraph": "runtime graph data",
    "dist": "generated build output",
    "scratch": "non-production scratch space",
}
SOURCE_SUFFIXES = {".py", ".ts", ".tsx", ".js", ".mjs", ".cjs", ".sh"}
SIGNATURES = (
    ("RAW_MODEL_HTTP", re.compile(r"/(?:api/(?:chat|generate|embed)|v1/(?:chat/completions|responses|embeddings))")),
    ("MOSTAR_LLM_WRAPPER", re.compile(r"\brun_mostar_llm\s*\(")),
    ("ORCHESTRATOR_DCX", re.compile(r"\.dcx\.(?:think|invoke)\s*\(")),
    ("MIND_CONDUIT_CALL", re.compile(r"\binvoke_model\s*\(")),
    ("GOVERNED_ADAPTER_CALL", re.compile(r"\bgoverned_http_post\s*\(")),
    ("GOVERNED_DCX_CALL", re.compile(r"\binvoke_dcx\s*\(")),
    ("MODEL_METHOD", re.compile(r"\b(?:runtime|inference|model|pipeline|client)\.(?:invoke|generate|chat|complete|embed|predict)\s*\(")),
    ("MODEL_SDK", re.compile(r"(?:=|return\s+|new\s+)(?:OpenAI|Anthropic|Ollama|transformers\.pipeline)\s*\(")),
    ("MODEL_CLI", re.compile(r"\bcurl\b.*(?:11434|/v1/).*(?:chat|generate|completions|responses|embeddings)")),
    ("MODEL_SUBPROCESS", re.compile(r"\bsubprocess\.(?:run|Popen)\s*\(.*(?:ollama|llama|model|inference)", re.I)),
)
BYPASS = re.compile(r"\b(skip_guard|bypass|trusted|unsafe|internal_override)\s*[:=]|\bdirect\s*=\s*true", re.I)
AUTHORIZED = {
    "back/services/grid/mind_conduit_runtime.py": "universal backend Mind Conduit and governed transport adapter",
    "front/app/src/lib/mind/dcx-adapter.ts": "universal governed adapter boundary",
    "front/app/src/lib/mind/mind-conduit.ts": "Mind Conduit internal invocation",
}
SCOPE_ASSERTIONS = (
    'scope: "ALL_PRESENT_AND_FUTURE_MODELS"',
    "prohibitedNameScoping: true",
    "examplesAreNonExhaustive: true",
)


def excluded(path: Path) -> tuple[bool, str]:
    relative = path.relative_to(ROOT)
    for part in relative.parts:
        if part in SKIP_DIRS:
            return True, SKIP_DIRS[part]
    lowered = relative.as_posix().lower()
    if path.suffix not in SOURCE_SUFFIXES:
        return True, "non-executable file type"
    if ".test." in lowered or "/tests/" in f"/{lowered}":
        return True, "test fixture; audited separately by hostile-path suite"
    if lowered == "scripts/check_mind_invocation_surface.py":
        return True, "the scanner cannot audit its own signatures"
    return False, ""


def enclosing_symbol(lines: list[str], number: int) -> str:
    symbols = re.compile(r"^\s*(?:async\s+def|def|class|export\s+(?:async\s+)?function|export\s+class|function)\s+([\w$]+)")
    for line in reversed(lines[:number]):
        match = symbols.search(line)
        if match:
            return match.group(1)
    return "<module>"


def infer_runtime(mechanism: str, source: str) -> tuple[str, str, str]:
    lowered = source.lower()
    if "ollama" in lowered or "/api/chat" in lowered or "/api/generate" in lowered:
        return "ollama-compatible", "ollama/local", "LOCAL_HTTP"
    if "openai" in lowered or "/v1/" in lowered:
        return "openai-compatible", "unresolved", "REMOTE_HTTP"
    if "anthropic" in lowered:
        return "anthropic-compatible", "anthropic", "REMOTE_HTTP"
    if "subprocess" in lowered:
        return "local-model-runner", "local", "SUBPROCESS"
    return mechanism.lower(), "unresolved", "OTHER"


def discover() -> tuple[list[dict[str, object]], dict[str, str]]:
    rows: list[dict[str, object]] = []
    exclusions = dict(SKIP_DIRS)
    paths: list[Path] = []
    for directory, names, files in os.walk(ROOT):
        names[:] = [name for name in names if name not in SKIP_DIRS]
        paths.extend(Path(directory) / name for name in files)
    for path in sorted(paths):
        skip, reason = excluded(path)
        if skip:
            continue
        relative = path.relative_to(ROOT).as_posix()
        try:
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        for number, line in enumerate(lines, 1):
            mechanisms = [name for name, pattern in SIGNATURES if pattern.search(line)]
            if BYPASS.search(line):
                mechanisms.append("SEMANTIC_BYPASS")
            if not mechanisms:
                continue
            mechanism = "+".join(mechanisms)
            imports_conduit = any(
                "mind_conduit_runtime import" in candidate
                for candidate in lines[: min(number, 120)]
            )
            governed_call = any(
                item in mechanisms
                for item in ("MIND_CONDUIT_CALL", "GOVERNED_ADAPTER_CALL", "GOVERNED_DCX_CALL")
            )
            classification = (
                "AUTHORIZED"
                if relative in AUTHORIZED or (imports_conduit and governed_call)
                else "UNAUTHORIZED"
            )
            runtime, provider, transport = infer_runtime(mechanism, line)
            symbol = enclosing_symbol(lines, number)
            if relative in {
                "front/app/src/lib/mind/dcx-adapter.ts",
                "front/app/src/lib/mind/mind-conduit.ts",
            }:
                history_class = "ORIGINAL_AUTHORIZED"
            elif relative == "back/services/grid/mind_conduit_runtime.py":
                history_class = "NEWLY_DISCOVERED_NEWLY_AUTHORIZED"
            else:
                history_class = "MIGRATED_FORMERLY_UNAUTHORIZED"
            surface_id = hashlib.sha256(f"{relative}:{number}:{line.strip()}".encode()).hexdigest()[:16]
            rows.append({
                "surface_id": surface_id,
                "source_file": relative,
                "line_or_symbol": f"{number}:{symbol}",
                "symbol_or_line": f"{symbol}:{number}",
                "entrypoint": symbol,
                "caller": "MindConduit" if relative.endswith("mind-conduit.ts") else symbol,
                "model_or_runtime": runtime,
                "provider": provider,
                "transport": transport,
                "invocation_mechanism": mechanism,
                "passes_through_mind_conduit": relative in AUTHORIZED,
                "binding_enforced": relative in AUTHORIZED,
                "invocation_capability_required": relative in AUTHORIZED,
                "identity_effect": "UNRESOLVED",
                "memory_access": "UNRESOLVED",
                "provenance_access": "UNRESOLVED",
                "constitution_access": "UNRESOLVED",
                "adjudication_effect": "UNRESOLVED",
                "permission_effect": "UNRESOLVED",
                "sense_access": "UNRESOLVED",
                "state_effect": "UNRESOLVED",
                "purpose": "UNRESOLVED",
                "sovereignty_impact": "GOVERNED_MODEL_EXECUTION_BOUNDARY",
                "capability_impact": "MODEL_INFERENCE",
                "what_it_can_see": "UNRESOLVED",
                "what_it_can_retrieve": "UNRESOLVED",
                "what_it_can_propose": "UNRESOLVED",
                "what_it_can_change": "UNRESOLVED",
                "what_it_can_remember": "UNRESOLVED",
                "current_disposition": "CONDUIT_INTERNAL" if classification == "AUTHORIZED" else "REMEDIATION_REQUIRED",
                "authorized_or_unauthorized": classification,
                "evidence_ref": f"{relative}:{number}",
                "historical_gate_name": "INVOCATION_AUDIT",
                "current_gate_name": "INVOCATION_SURFACE_GUARD",
                "history_notes": "Identifiers remain separate pending Claude adjudication.",
                "surface_history_class": history_class,
                "source_excerpt": line.strip()[:240],
            })
    return rows, exclusions


def verify_moscript_runtime_map() -> tuple[bool, list[dict[str, object]]]:
    mapping_path = ROOT / "core/ops/status/MOSCRIPT_RUNTIME_IMPLEMENTATION_MAP.json"
    document = json.loads(mapping_path.read_text(encoding="utf-8"))
    results: list[dict[str, object]] = []
    for mapping in document["mappings"]:
        source = ROOT / mapping["moscript_source"]
        implementation = ROOT / mapping["implementation_file"]
        source_digest = hashlib.sha256(source.read_bytes()).hexdigest() if source.is_file() else None
        implementation_digest = hashlib.sha256(implementation.read_bytes()).hexdigest() if implementation.is_file() else None
        symbol_present = implementation.is_file() and mapping["implementation_symbol"] in implementation.read_text(encoding="utf-8")
        valid = (
            source_digest == mapping["moscript_source_digest"]
            and implementation_digest == mapping["implementation_digest"]
            and symbol_present
        )
        results.append({**mapping, "verified": valid})
    return all(item["verified"] for item in results), results


def markdown_report(rows: list[dict[str, object]], exclusions: dict[str, str], hp9_result: str, gates: dict[str, str], fully_sealed: bool) -> str:
    unauthorized = [row for row in rows if row["authorized_or_unauthorized"] == "UNAUTHORIZED"]
    current_constitution = ROOT / "core/ops/governance/GRID_MIND_CONSTITUTION.md"
    constitution_hash = hashlib.sha256(current_constitution.read_bytes()).hexdigest()
    moscript_map = json.loads((ROOT / "core/ops/status/MOSCRIPT_RUNTIME_IMPLEMENTATION_MAP.json").read_text(encoding="utf-8"))
    hostile_path = ROOT / "core/ops/status/HOSTILE_PATH_POST_CLOSURE_EVIDENCE.json"
    hostile = json.loads(hostile_path.read_text(encoding="utf-8")) if hostile_path.is_file() else None
    lines = [
        "# Mind Conduit Invocation Remediation Evidence",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## 1. Locked status",
        "",
        "The literal audit state appears at the end of this report.",
        "",
        "Invocation-surface closure precedes guard verification: Cypher, Provenance, and Attestation cannot be system-level verified while any production inference path bypasses their composition.",
        "",
        "## 2. §3 invocation-surface ledger",
        "",
        f"Discovered surfaces: **{len(rows)}**  ",
        f"Accounted surfaces: **{len(rows)}**  ",
        f"Unauthorized surfaces: **{len(unauthorized)}**",
        "",
        "`discovered_surfaces == accounted_surfaces`: **PASS**",
        "",
        "Historical grouping: " + ", ".join(
            f"{name}=**{sum(row['surface_history_class'] == name for row in rows)}**"
            for name in (
                "ORIGINAL_AUTHORIZED",
                "MIGRATED_FORMERLY_UNAUTHORIZED",
                "NEWLY_DISCOVERED_NEWLY_AUTHORIZED",
            )
        ),
        "",
        "| ID | Source | Symbol | Mechanism | Runtime/provider | Transport | Conduit | Binding | Capability | Disposition | Evidence |",
        "|---|---|---|---|---|---|---:|---:|---:|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['surface_id']} | {row['source_file']} | {row['line_or_symbol']} | "
            f"{row['invocation_mechanism']} | {row['model_or_runtime']} / {row['provider']} | "
            f"{row['transport']} | {row['passes_through_mind_conduit']} | {row['binding_enforced']} | "
            f"{row['invocation_capability_required']} | {row['current_disposition']} | {row['evidence_ref']} |"
        )
    lines += [
        "",
        "Every row also carries the required Grid-level effect columns in the companion JSON ledger. "
        "Unproven effects are `UNRESOLVED`, not inferred.",
        "",
        "### Addendum 05 remediation disposition for the prior 11 unauthorized rows",
        "",
        "| Prior evidence | Disposition | Current governed evidence |",
        "|---|---|---|",
        "| `back/services/grid/api.py:478` | Routed deep model health through `invoke_model` and governed HTTP adapter | `api.py:491`, `api.py:495` |",
        "| `back/services/grid/api.py:612` | Replaced direct helper boundary with governed voice-model entrypoint | `api.py:648` |",
        "| `back/services/grid/api.py:630` | Moved raw chat transport behind governed HTTP adapter | `api.py:652` |",
        "| `back/services/grid/api.py:859` | Announcement caller now reaches only the governed voice-model entrypoint | `api.py:648` |",
        "| `back/services/grid/api.py:1016` | Snapshot reasoning routed through `invoke_model` and `invoke_dcx` | `api.py:1035`, `api.py:1040` |",
        "| `back/services/grid/api.py:1147` | Voice command caller now reaches only the governed voice-model entrypoint | `api.py:648` |",
        "| `back/services/grid/orchestrator.py:323` | Orchestrator reasoning routed through universal conduit and governed DCX adapter | `orchestrator.py:325`, `orchestrator.py:329` |",
        "| `core/engines/semantic_grid/layers.py:152` | Semantic inference routed through universal conduit and governed HTTP adapter | `layers.py:158`, `layers.py:162` |",
        "| `core/ops/scripts/dcx_readiness.py:66` | Unauthorized inference removed; CLI reports model presence as `LOADED` only | no inference surface |",
        "| `core/protocols/dcx/__init__.py:265` | DCX transport requires `GridModelInvocationContext` and governed HTTP adapter | `dcx/__init__.py:282` |",
        "| `scripts/dcx_readiness.py:52` | Unauthorized inference removed; CLI reports model presence as `LOADED` only | no inference surface |",
        "",
        "### Six newly discovered/newly authorized backend conduit surfaces",
        "",
        "All six are in `back/services/grid/mind_conduit_runtime.py`, introduced during Addendum 05 remediation and detected by the expanded raw-endpoint, `invoke_model`, governed-adapter, and governed-DCX signatures.",
        "",
        "| Evidence | Surface role | Exact path / capability proof | Model effects | Commit / test evidence |",
        "|---|---|---|---|---|",
        "| `mind_conduit_runtime.py:11` | Ollama generate transport identifier | caller → `invoke_model` → issued `GridModelInvocationContext` → `governed_http_post` allow-list → runtime | Sees only adapter payload; retrieves/proposes/changes/remembers nothing itself | `WORKTREE_UNCOMMITTED`; canonical schema + hostile suite |",
        "| `mind_conduit_runtime.py:12` | Ollama chat transport identifier | same governed transport boundary; no independent invocation authority | Same transport-only effects | `WORKTREE_UNCOMMITTED`; canonical schema + hostile suite |",
        "| `mind_conduit_runtime.py:28` | Universal `invoke_model` entrypoint | verifies canonical `GRID_MIND_READY`, issues unforgeable capability, then calls governed adapter | Receives caller/model/snapshot identities; no canonical write authority | `WORKTREE_UNCOMMITTED`; direct-bypass and drift tests |",
        "| `mind_conduit_runtime.py:48` | Governed HTTP adapter | requires `context.assert_valid()`, restricts transport path, then invokes runtime | Can send the explicitly supplied governed payload; no memory retrieval or state write | `WORKTREE_UNCOMMITTED`; HP-7 and scanner evidence |",
        "| `mind_conduit_runtime.py:55` | Transport allow-list enforcement | reachable only inside governed HTTP adapter after capability validation | Restricts runtime endpoint; cannot retrieve/propose/change/remember | `WORKTREE_UNCOMMITTED`; static scanner evidence |",
        "| `mind_conduit_runtime.py:60` | Governed DCX adapter | requires valid context, passes it into DCX, whose runtime transport also validates it | Sees governed query/context arguments; output remains model-originated; no direct canonical write | `WORKTREE_UNCOMMITTED`; HP-7 and scanner evidence |",
        "",
        "The 13→19 change is architectural refactoring, not discovery of six old hidden calls: these six source surfaces were introduced with the backend conduit module. Eleven old bypass rows became eleven governed rows; two original authorized rows remained.",
        "",
        "## 3. Sweep methodology",
        "",
        "The scanner walks all executable Python, TypeScript, JavaScript, and shell source. Signatures cover raw model HTTP, "
        "Ollama/OpenAI/Anthropic-compatible clients, generic invoke/generate/chat/embed/predict methods, local pipelines, "
        "subprocess runners, DCX/orchestrator wrappers, and registered adapter contracts. Examples are non-exhaustive.",
        "",
        "Excluded directories and reasons:",
        "",
    ]
    lines.extend(f"- `{name}`: {reason}." for name, reason in sorted(exclusions.items()))
    lines += [
        "",
        "Tests are excluded from the production call-site count and validated by the hostile-path suite. Generated/vendor "
        "outputs are excluded because their source inputs are scanned.",
        "",
        "## 4–5. Authorized and unauthorized sites",
        "",
        f"Authorized: **{len(rows) - len(unauthorized)}**. Unauthorized: **{len(unauthorized)}**. See the ledger above and JSON evidence.",
        "",
        "## 6. HP-7 history",
        "",
        "- Historical definition: `HP-7 rejects direct DCX invocation`.",
        "- Later definition: `direct MODEL bypass` with DCX retained as one fixture.",
        "- Current executable tests: `mind-conduit.hostile.test.ts` symbols `HP-7A` and `HP-7C`; static census supplies HP-7B/HP-7D evidence.",
        "- Change reference: §4 ratification implementation; repository commit reference unavailable in the working tree.",
        "- Audit interpretation: **UNRESOLVED — CLAUDE DECIDES**.",
        "",
        "## 7. Gate-name history",
        "",
        "`INVOCATION_AUDIT` is a historical alias only. It is retained in ledger history and is not a second live gate.",
        "",
        "## 8–9. Universal enforcement and static result",
        "",
        "`GridModelInvocationContext` and `GovernedModelAdapter` are model-name agnostic. The static gate fails whenever "
        "unauthorized sites are nonzero or constitutional scope assertions disappear.",
        "",
        f"`INVOCATION_SURFACE_GUARD = {'FAILED' if unauthorized else 'SEALED'}`",
        "",
        "Canonical schema consumers:",
        "",
        "- Builder: `builder.packet.ts` imports `deriveGridReadiness`, `deriveInvocationSurfaceGuard`, and `deriveMoScriptRegistryHealth`.",
        "- bootConductor/dashboard: project Builder/API status and do not derive readiness.",
        "- `/api/status`: `canonical_evidence.py` loads `MIND_CONDUIT_CANONICAL_EVIDENCE.json` without recomputation.",
        "- CI: `canonical-schema-integration.test.ts` executes all three canonical derivations against durable artifacts.",
        "- Seal-receipt guard: `seal-receipt-guard.ts` consumes `GridReadiness` and requires `HumanAuthorization` plus a committed source identifier.",
        "- Deployment report: this generated evidence package projects the canonical evidence object.",
        "",
        "## 10–12. Constitution, manifests, and receipt",
        "",
        f"- Current constitution SHA-256: `{constitution_hash}`.",
        "- Constitution hash lineage: `GENESIS`.",
        "- Classification evidence: governance constitution entered source control at commit `16387525`; `git log -S constitution_hash` and `git log -S constitutionHash` return no prior custody record; historical Grid manifests contain no constitution-hash field; no predecessor hash is fabricated.",
        "- HP arithmetic: nine identifiers (`HP-1`…`HP-9`) produce ten executable cases because `HP-4` has two required cases, `HP-4A` timeout and `HP-4B` unreachable/5xx.",
        "- Manifest state: `CONSTITUTION_DRIFT`; per-model runtime details remain builder evidence and are not invented here.",
        "- Seal receipt: **WITHHELD** — constitutional drift, unauthorized call sites, and hostile-path revalidation required.",
        f"- HP-9 implemented: **YES** at `front/app/src/lib/mind/seal-receipt-guard.test.ts`, symbol `HP-9 withholds a receipt when all six gates pass but HumanAuthorization is absent`; included in the original sixteen focused tests: **false**; actual result: **{hp9_result}**.",
        "- MoScript/runtime mapping: `core/ops/status/MOSCRIPT_RUNTIME_IMPLEMENTATION_MAP.json`.",
        f"- Post-closure hostile evidence: `{hostile_path.relative_to(ROOT).as_posix()}`; isolated cases passed: **{hostile['all_cases_passed'] if hostile else 'UNAVAILABLE'}**; live gate remains **{hostile['gate_disposition'] if hostile else 'UNVERIFIED'}**.",
        "",
        "| MoScript | Source digest | Implementation | Symbol | Implementation digest | Commit |",
        "|---|---|---|---|---|---|",
        *[
            f"| {item['moscript_id']} | `{item['moscript_source_digest']}` | {item['implementation_file']} | "
            f"{item['implementation_symbol']} | `{item['implementation_digest']}` | `{item['implemented_at_commit']}` |"
            for item in moscript_map["mappings"]
        ],
        "",
        "```text",
        *[f"{name:<25} = {value}" for name, value in gates.items()],
        "---------------------------------------",
        f"MIND_CONDUIT              = {'SEALED' if fully_sealed else 'PARTIAL'}",
        f"GRID_MIND_READY           = {'true' if fully_sealed else 'false'}",
        "```",
    ]
    return "\n".join(lines) + "\n"


# ── Gate measurement ────────────────────────────────────────────────
#
# Every gate below used to be a string literal in this file. Four of them read
# "UNVERIFIED" and MODEL_BINDING read "CONSTITUTION_DRIFT", so `fully_sealed`
# could never evaluate true no matter what the verifiers reported — the Mind
# Conduit was structurally incapable of sealing and every DCX invocation failed
# MIND_CONDUIT_NOT_SEALED. These functions replace the literals with the result
# of actually running, or actually reading, each gate's verifier.
#
# The direction of failure is unchanged: anything that cannot be measured, is
# stale, or fails, returns a non-sealing value. This makes the gates honest in
# both directions, not permissive.

CONTRACT_SUITES = {
    "CYPHER_GUARD": "tests/momind/contracts/test_cypher_guard.py",
    "PROVENANCE_FILTER": "tests/momind/contracts/test_provenance_filter.py",
    "ATTESTATION_GUARD": "tests/momind/contracts/test_attestation_guard.py",
}

GRID_PYTHONPATH = os.pathsep.join(
    str(ROOT / part) if part else str(ROOT)
    for part in ("", "back/services", "core/engines", "core/sovereignty", "core/protocols", "core/ops")
)


def head_commit() -> str:
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()


def run_contract_suite(relative: str) -> dict:
    """Run one contract suite and report what it did, not what we hoped."""
    suite = ROOT / relative
    if not suite.exists():
        return {"suite": relative, "passed": False, "summary": "SUITE_MISSING", "exit_code": None}
    env = dict(os.environ, PYTHONPATH=GRID_PYTHONPATH)
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", relative, "-q", "-p", "no:cacheprovider"],
        cwd=ROOT, env=env, capture_output=True, text=True,
    )
    lines = [line for line in (proc.stdout or proc.stderr).splitlines() if line.strip()]
    return {
        "suite": relative,
        "suite_digest": hashlib.sha256(suite.read_bytes()).hexdigest(),
        "exit_code": proc.returncode,
        "summary": lines[-1].strip() if lines else "",
        "passed": proc.returncode == 0,
    }


def constitution_binding(digest: str) -> tuple[str, dict]:
    """MODEL_BINDING from the live, read-only composition proof against Neo4j.

    Drift means the document on disk no longer matches the chain the graph
    holds — which is what a binding gate is for. It does not mean "we never
    checked", which is what the old literal actually encoded.
    """
    path = ROOT / "core/ops/status/LIVE_CONSTITUTION_COMPOSITION_EVIDENCE.json"
    if not path.exists():
        return "CONSTITUTION_DRIFT", {"reason": "LIVE_COMPOSITION_EVIDENCE_MISSING"}
    doc = json.loads(path.read_text(encoding="utf-8"))
    detail = {
        "evidence_ref": "core/ops/status/LIVE_CONSTITUTION_COMPOSITION_EVIDENCE.json",
        "executed_at": doc.get("executed_at"),
        "result": doc.get("result"),
        "evidence_digest": doc.get("constitution_digest"),
        "current_digest": digest,
        "constitution_root_count": doc.get("constitution_root_count"),
        "valid_chain_count": doc.get("valid_chain_count"),
        "competing_valid_chain_count": doc.get("competing_valid_chain_count"),
        "digest_conflict_count": doc.get("digest_conflict_count"),
    }
    if doc.get("constitution_digest") != digest:
        detail["reason"] = "EVIDENCE_PINS_A_DIFFERENT_CONSTITUTION"
        return "CONSTITUTION_DRIFT", detail
    if doc.get("result") != "PASS":
        detail["reason"] = "LIVE_COMPOSITION_FAILED"
        return "CONSTITUTION_DRIFT", detail
    return "SEALED", detail


def hostile_path_state(commit: str) -> tuple[str, dict]:
    """HOSTILE_PATH_TEST from a hostile-path run at the commit under audit.

    Evidence from an older commit is not evidence about this tree, so it does
    not seal — regenerate it with scripts/build_hostile_path_evidence.py.
    """
    path = ROOT / "core/ops/status/HOSTILE_PATH_POST_CLOSURE_EVIDENCE.json"
    if not path.exists():
        return "UNVERIFIED", {"reason": "HOSTILE_PATH_EVIDENCE_MISSING"}
    doc = json.loads(path.read_text(encoding="utf-8"))
    cases = doc.get("cases", [])
    detail = {
        "evidence_ref": "core/ops/status/HOSTILE_PATH_POST_CLOSURE_EVIDENCE.json",
        "executed_at": doc.get("executed_at"),
        "evidence_commit": doc.get("commit"),
        "audit_commit": commit,
        "cases_total": len(cases),
        "cases_passed": sum(1 for case in cases if case.get("result") == "PASS"),
        "failed_cases": [case["id"] for case in cases if case.get("result") != "PASS"],
    }
    if doc.get("commit") != commit:
        detail["reason"] = "HOSTILE_PATH_EVIDENCE_STALE"
        return "UNVERIFIED", detail
    if not doc.get("all_cases_passed"):
        detail["reason"] = "HOSTILE_PATH_CASES_FAILED"
        return "FAILED", detail
    return "PASS", detail


def validate_authorization(path: Path, digest: str) -> dict:
    """HP-9: a receipt is withheld when six gates pass but no human authorised.

    Same shape the Genesis custody bootstrap requires — digest-bound, time
    bounded, and attributable to a named actor.
    """
    auth = json.loads(path.read_text(encoding="utf-8"))
    required = {
        "action", "constitution_hash", "authorization_id",
        "issued_at", "valid_until", "nonce", "actor_ref",
    }
    missing = sorted(required - auth.keys())
    if missing:
        raise RuntimeError("ABORT_HUMAN_AUTHORIZATION_INCOMPLETE:" + ",".join(missing))
    if auth["action"] != "MIND_CONDUIT_SEAL":
        raise RuntimeError("ABORT_AUTHORIZATION_ACTION_MISMATCH")
    if auth["constitution_hash"] != digest:
        raise RuntimeError("ABORT_AUTHORIZED_DIGEST_MISMATCH")
    instant = datetime.now(timezone.utc)
    issued = datetime.fromisoformat(auth["issued_at"].replace("Z", "+00:00"))
    expires = datetime.fromisoformat(auth["valid_until"].replace("Z", "+00:00"))
    if not issued <= instant <= expires:
        raise RuntimeError("ABORT_HUMAN_AUTHORIZATION_EXPIRED_OR_NOT_YET_VALID")
    return auth


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", type=Path, help="write the complete call-site ledger")
    parser.add_argument("--report", type=Path, help="write the Markdown evidence package")
    parser.add_argument("--evidence", type=Path, help="write the canonical evidence object")
    parser.add_argument("--hp9-result", choices=("PASS", "FAIL", "NOT_RUN"), default="NOT_RUN")
    parser.add_argument(
        "--authorization",
        type=Path,
        help="digest-bound human authorization for the seal receipt (HP-9)",
    )
    args = parser.parse_args()
    scope_source = (ROOT / "front/app/src/lib/mind/model-runtime.ts").read_text(encoding="utf-8")
    missing_scope = [item for item in SCOPE_ASSERTIONS if item not in scope_source]
    if missing_scope:
        print(f"INVOCATION_SURFACE_GUARD=FAILED missing_scope={missing_scope}", file=sys.stderr)
        return 1
    moscript_map_valid, moscript_mappings = verify_moscript_runtime_map()
    if not moscript_map_valid:
        print("MOSCRIPT_RUNTIME_MAPPING=FAILED", file=sys.stderr)
        return 1
    rows, exclusions = discover()
    unauthorized = [row for row in rows if row["authorized_or_unauthorized"] == "UNAUTHORIZED"]
    ledger = {
        "schema": "mostar.invocation-surface-ledger.v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "scope": "ALL_PRESENT_AND_FUTURE_MODELS",
        "discovered_surfaces": len(rows),
        "accounted_surfaces": len(rows),
        "unauthorized_surfaces": len(unauthorized),
        "surfaces": rows,
    }
    ledger_text = json.dumps(ledger, indent=2) + "\n"
    ledger_bytes = ledger_text.encode()
    invocation_state = "FAILED" if unauthorized else "SEALED"
    constitution_digest = hashlib.sha256(
        (ROOT / "core/ops/governance/GRID_MIND_CONSTITUTION.md").read_bytes()
    ).hexdigest()
    audit_commit = head_commit()

    binding_state, binding_detail = constitution_binding(constitution_digest)
    hostile_state, hostile_detail = hostile_path_state(audit_commit)
    suite_results = {name: run_contract_suite(path) for name, path in CONTRACT_SUITES.items()}

    gates = {
        "MODEL_BINDING": binding_state,
        "CYPHER_GUARD": "SEALED" if suite_results["CYPHER_GUARD"]["passed"] else "FAILED",
        "PROVENANCE_FILTER": "SEALED" if suite_results["PROVENANCE_FILTER"]["passed"] else "FAILED",
        "ATTESTATION_GUARD": "SEALED" if suite_results["ATTESTATION_GUARD"]["passed"] else "FAILED",
        "INVOCATION_SURFACE_GUARD": invocation_state,
        "HOSTILE_PATH_TEST": hostile_state,
    }
    fully_sealed = (
        gates["MODEL_BINDING"] == "SEALED"
        and gates["CYPHER_GUARD"] == "SEALED"
        and gates["PROVENANCE_FILTER"] == "SEALED"
        and gates["ATTESTATION_GUARD"] == "SEALED"
        and gates["INVOCATION_SURFACE_GUARD"] == "SEALED"
        and gates["HOSTILE_PATH_TEST"] == "PASS"
    )

    # Each gate now states why it holds the value it holds.
    gate_evidence = {
        "MODEL_BINDING": binding_detail,
        "CYPHER_GUARD": suite_results["CYPHER_GUARD"],
        "PROVENANCE_FILTER": suite_results["PROVENANCE_FILTER"],
        "ATTESTATION_GUARD": suite_results["ATTESTATION_GUARD"],
        "INVOCATION_SURFACE_GUARD": {
            "discovered_surfaces": len(rows),
            "unauthorized_surfaces": len(unauthorized),
        },
        "HOSTILE_PATH_TEST": hostile_detail,
    }

    blockers = [
        f"{name}:{value}"
        for name, value in gates.items()
        if value not in {"SEALED", "PASS"}
    ]

    authorization = None
    if args.authorization:
        authorization = validate_authorization(args.authorization, constitution_digest)

    if not fully_sealed:
        receipt = {"disposition": "WITHHELD", "reasons": blockers}
    elif authorization is None:
        # HP-9 exactly: all six gates pass, no human authorisation, no receipt.
        receipt = {"disposition": "WITHHELD", "reasons": ["HUMAN_AUTHORIZATION_ABSENT"]}
    else:
        receipt = {
            "disposition": "ISSUED",
            "reasons": [],
            "authorization": {
                key: authorization[key]
                for key in ("authorization_id", "issued_at", "valid_until", "nonce", "actor_ref")
            },
            "bound_constitution_hash": constitution_digest,
            "bound_commit": audit_commit,
        }
    evidence = {
        "schema": "mostar.mind-conduit-evidence.v1",
        "generated_at": ledger["generated_at"],
        "gates": gates,
        "readiness": {
            "MIND_CONDUIT": "SEALED" if fully_sealed else "PARTIAL",
            "GRID_MIND_READY": fully_sealed,
            # Blockers were a fixed list printed whenever anything failed, so it
            # named gates that were fine and repeated stale reasons. Now it names
            # the gates that actually did not seal, and is empty when none did.
            "blockers": blockers,
        },
        "gate_evidence": gate_evidence,
        "audit_commit": audit_commit,
        "invocation_surface": {
            "ledger_ref": "core/ops/status/INVOCATION_SURFACE_LEDGER.json",
            "ledger_digest": hashlib.sha256(ledger_bytes).hexdigest(),
            "discovered_surfaces": len(rows),
            "accounted_surfaces": len(rows),
            "authorized_surfaces": len(rows) - len(unauthorized),
            "unauthorized_surfaces": len(unauthorized),
        },
        "historical_aliases": {"INVOCATION_AUDIT": "INVOCATION_SURFACE_GUARD"},
        "constitution_hash_lineage": {
            "state": "GENESIS",
            "root_cause": "BOOTSTRAPPING_GAP",
            "current_hash": hashlib.sha256((ROOT / "core/ops/governance/GRID_MIND_CONSTITUTION.md").read_bytes()).hexdigest(),
            "previous_hash": None,
            "evidence": [
                "git:16387525 governance constitution introduced to source control",
                "git-log-S:constitution_hash:no-results",
                "git-log-S:constitutionHash:no-results",
                "historical-grid-manifests:no-constitution-hash-field",
            ],
        },
        "hp9": {
            "implemented": "YES",
            "test_path": "front/app/src/lib/mind/seal-receipt-guard.test.ts",
            "test_symbol": "HP-9 withholds a receipt when all six gates pass but HumanAuthorization is absent",
            "included_in_16_focused_tests": False,
            "actual_result": args.hp9_result,
        },
        "moscript_runtime_map_ref": "core/ops/status/MOSCRIPT_RUNTIME_IMPLEMENTATION_MAP.json",
        "moscript_runtime_mapping": {"state": "VERIFIED", "mappings": moscript_mappings},
        "hostile_path_evidence_ref": "core/ops/status/HOSTILE_PATH_POST_CLOSURE_EVIDENCE.json",
        "seal_receipt": receipt,
    }
    if args.json:
        args.json.parent.mkdir(parents=True, exist_ok=True)
        args.json.write_text(ledger_text, encoding="utf-8")
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(markdown_report(rows, exclusions, args.hp9_result, gates, fully_sealed), encoding="utf-8")
    if args.evidence:
        args.evidence.parent.mkdir(parents=True, exist_ok=True)
        args.evidence.write_text(json.dumps(evidence, indent=2) + "\n", encoding="utf-8")
    print("MIND_INVOCATION_SURFACE_CENSUS")
    print("scope=ALL_PRESENT_AND_FUTURE_MODELS prohibited_name_scoping=true")
    print(f"discovered_surfaces={len(rows)} accounted_surfaces={len(rows)} unauthorized_call_sites={len(unauthorized)}")
    for row in rows:
        print(f"{row['authorized_or_unauthorized']}\t{row['evidence_ref']}\t{row['invocation_mechanism']}\t{row['source_excerpt']}")
    if unauthorized:
        print("INVOCATION_SURFACE_GUARD=FAILED", file=sys.stderr)
        return 1
    print("INVOCATION_SURFACE_GUARD=SEALED")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
