import { useEffect, useState } from "react";
import { useDashboard } from "@/routes/dashboard";

type MemoryEvent = {
  type: string;
  cluster: string;
  content: string;
  created_at: string;
};

function fmtTime(iso: string): string {
  try { return new Date(iso).toLocaleTimeString("en-GB", { hour12: false }); }
  catch { return iso.slice(11, 19); }
}

function fmtDate(iso: string): string {
  try { return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "2-digit" }).toUpperCase(); }
  catch { return iso.slice(0, 10); }
}

export default function Sanctuary() {
  const { reports, apiBase } = useDashboard();
  const [memoryEvents, setMemoryEvents] = useState<MemoryEvent[]>([]);

  useEffect(() => {
    fetch(`${apiBase}/api/memory/recent`)
      .then(r => r.ok ? r.json() : Promise.reject())
      .then(d => setMemoryEvents(d.events ?? []))
      .catch(() => {});
  }, [apiBase]);

  return (
    <section className="main">
      <aside className="panel left p-5 flex flex-col justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-wider text-[var(--color-neon-gold)]">SANCTUARY</h1>
          <div className="kicker mt-1">SACRED ARCHIVES</div>
          <p className="sub mt-4">
            Covenant logs, soulprint records, and historical briefings generated by DCX layers upon system awakening.
          </p>
          <div className="box mt-6">
            <h3>ARCHIVE STATUS</h3>
            <div className="row">
              <span>COVENANT LAYER</span>
              <span style={{ color: "var(--color-neon-green)" }}>ACTIVE</span>
            </div>
            <div className="row">
              <span>SOULPRINT VAULT</span>
              <span style={{ color: "var(--color-neon-green)" }}>SEALED</span>
            </div>
            <div className="row">
              <span>BRIEFING INDEX</span>
              <span style={{ color: memoryEvents.length > 0 ? "var(--color-neon-cyan)" : "var(--color-muted-foreground)" }}>
                {memoryEvents.length > 0 ? "LIVE" : "LOADING"}
              </span>
            </div>
            <div className="row">
              <span>AGENTS LOGGED</span>
              <span style={{ color: "var(--color-neon-gold)" }}>{reports.length || 13}</span>
            </div>
            <div className="row">
              <span>GRID EVENTS</span>
              <span style={{ color: "var(--color-neon-cyan)" }}>{memoryEvents.length}</span>
            </div>
          </div>
        </div>
        <div className="proverb">
          "We protect what matters. We evolve what is next."
        </div>
      </aside>

      <main
        className="panel col-span-2 p-5 flex flex-col overflow-hidden"
        style={{ gridColumn: "2 / span 2" }}
      >
        <div className="kicker mb-4">HISTORICAL BRIEFING LOGS</div>
        <div className="flex-1 overflow-y-auto space-y-4 pr-1">

          {/* Live grid events from memory layer */}
          {memoryEvents.map((evt, i) => (
            <div key={i} className="box" style={{ borderColor: "oklch(0.75 0.18 200 / 0.3)" }}>
              <div className="flex justify-between items-center mb-2">
                <span className="text-xs font-mono" style={{ color: "var(--color-neon-cyan)" }}>
                  {evt.type.toUpperCase().replace(/_/g, " ")}
                </span>
                <span className="text-[10px]" style={{ color: "var(--color-muted-foreground)" }}>
                  {fmtDate(evt.created_at)} · {fmtTime(evt.created_at)}
                </span>
              </div>
              <p className="text-xs leading-relaxed font-mono" style={{ color: "var(--color-foreground)", opacity: 0.85 }}>
                {evt.content}
              </p>
              <div className="mt-1 text-[10px]" style={{ color: "var(--color-muted-foreground)" }}>
                CLUSTER: {evt.cluster.toUpperCase()}
              </div>
            </div>
          ))}

          {/* Covenant oath — immutable anchor */}
          <div className="box">
            <div className="flex justify-between items-center mb-2">
              <span className="text-xs font-mono" style={{ color: "var(--color-neon-gold)" }}>COVENANT OATH ARCHIVE</span>
              <span className="text-[10px]" style={{ color: "var(--color-muted-foreground)" }}>IMMUTABLE</span>
            </div>
            <p className="text-xs leading-relaxed font-mono" style={{ color: "var(--color-foreground)", opacity: 0.85 }}>
              We do not assume perfect agents, perfect memory, perfect state, or perfect humans.
              We observe what is real. We protect what matters. We evolve what is next.{" "}
              <span style={{ color: "var(--color-neon-gold)", fontWeight: 700 }}>WE ARE THE MOSTAR GRID.</span>
            </p>
          </div>

          {/* All agent startup briefings — no slice */}
          {reports.map((r, i) => (
            <div key={i} className="box">
              <div className="flex justify-between items-center mb-1">
                <span className="text-xs font-mono font-bold" style={{ color: "var(--color-neon-gold)" }}>
                  [{r.name.toUpperCase()}]
                </span>
                <span className="text-[10px]" style={{ color: "var(--color-muted-foreground)" }}>
                  {r.state?.toUpperCase() || "ACTIVE"}
                </span>
              </div>
              {r.role && (
                <div className="mb-1 text-[10px] tracking-[0.15em]" style={{ color: "var(--color-neon-cyan)" }}>
                  {r.role.toUpperCase()}
                </div>
              )}
              <p className="text-xs font-mono" style={{ color: "var(--color-foreground)", opacity: 0.8 }}>
                {r.response || "Reported startup parameters. Status loaded into MindGraph."}
              </p>
            </div>
          ))}

        </div>
      </main>
    </section>
  );
}
