import asyncio
import logging
import feedparser
from grid.config import MOSTAR_CLUSTER_ID, NEO4J_DATABASE
from grid.events import event_bus, GridEvent

logger = logging.getLogger("grid_watchers")

class MoodEngine:
    def __init__(self):
        self.current_mood = "stable"
        self.recent_events = []

    def observe(self, event: GridEvent):
        self.recent_events.append(event)
        if len(self.recent_events) > 10:
            self.recent_events.pop(0)
            
        # Very simple mood calculation based on recent severities
        high_critical = sum(1 for e in self.recent_events if e.severity in ["high", "critical"])
        
        if high_critical >= 2:
            self.current_mood = "critical"
        elif high_critical == 1:
            self.current_mood = "alert"
        else:
            self.current_mood = "stable"
            
        return self.current_mood

mood_engine = MoodEngine()

async def world_signal_watcher():
    """Polls RSS feeds for high severity events periodically."""
    logger.info("WorldSignalWatcher started.")
    last_top_headline = ""
    
    while True:
        try:
            africa_feed = feedparser.parse("https://feeds.bbci.co.uk/news/world/africa/rss.xml")
            if africa_feed.entries:
                top_entry = africa_feed.entries[0]
                headline = top_entry.title
                
                # Check if it's new
                if headline != last_top_headline:
                    last_top_headline = headline
                    
                    # Naive severity detection: words indicating crisis
                    crisis_words = ["flood", "war", "crisis", "attack", "death", "crash", "emergency"]
                    severity = "low"
                    if any(w in headline.lower() for w in crisis_words):
                        severity = "high"
                        
                    event = GridEvent(
                        type="world_signal",
                        severity=severity,
                        mood=mood_engine.current_mood, # will be updated on next observe
                        source="bbc_africa_rss",
                        text=headline,
                        payload={"url": top_entry.link},
                        source_type="live_api",
                        verification_status="unverified",
                        operational_trust="reference",
                        created_by="world_signal_watcher",
                        source_id=top_entry.link,
                    )
                    
                    mood = mood_engine.observe(event)
                    event.mood = mood # update with new mood
                    
                    await event_bus.publish(event)
                    
        except Exception as e:
            logger.error(f"WorldSignalWatcher error: {e}")
            
        # Poll every 5 minutes
        await asyncio.sleep(300)

async def telemetry_watcher(orchestrator):
    """Polls grid telemetry for anomalies."""
    logger.info("TelemetryWatcher started.")
    last_pulse = 100.0
    
    while True:
        try:
            # Let's say we have access to orchestrator status
            status = await orchestrator.status()
            
            # Simulated pulse drop check for demonstration. 
            # In reality, pulse is generated by ClusterTelemetry.
            mindgraph_ok = status.get("mindgraph", {}).get("status") == "connected"
            
            severity = "low"
            text = "Telemetry stable"
            
            if not mindgraph_ok:
                severity = "critical"
                text = "MindGraph connection lost!"
                
                event = GridEvent(
                    type="telemetry_alert",
                    severity=severity,
                    mood=mood_engine.current_mood,
                    source="telemetry_watcher",
                    text=text,
                    payload={"status": status},
                    source_type="runtime_generated",
                    verification_status="verified",
                    operational_trust="operational",
                    created_by="telemetry_watcher",
                )
                
                mood = mood_engine.observe(event)
                event.mood = mood
                
                await event_bus.publish(event)
                
        except Exception as e:
            logger.error(f"TelemetryWatcher error: {e}")
            
        # Poll every 30 seconds
        await asyncio.sleep(30)

async def executor_watcher(orchestrator):
    """Simulates the executor loop heartbeat while think() is disabled."""
    logger.info("ExecutorWatcher started.")
    while True:
        try:
            if orchestrator.mindgraph.connected:
                async with orchestrator.mindgraph._driver.session(database=NEO4J_DATABASE) as session:
                    await session.run("""
                        CREATE (h:ExecutorHeartbeat {
                            id: randomUUID(),
                            created_at: datetime(),
                            status: 'ALIVE',
                            cluster_id: $cluster_id,
                            source: 'executor_watcher',
                            source_type: 'runtime_generated',
                            created_by: 'executor_watcher',
                            verification_status: 'verified',
                            operational_trust: 'operational',
                            seal: 'Operational'
                        })
                    """, cluster_id=MOSTAR_CLUSTER_ID)
                # Cycles are tied to provenance records
        except Exception as e:
            logger.error(f"ExecutorWatcher error: {e}")

        await asyncio.sleep(60)

async def mindgraph_reconnect_watcher(orchestrator):
    """Retries the MindGraph connection if boot-time connect failed or it later drops.

    orchestrator.boot() only attempts the Neo4j connection once; if that single
    attempt fails (e.g. a transient outage during deploy), mindgraph.connected
    stays False for the lifetime of the process. This loop keeps retrying so a
    cloud DB hiccup at startup doesn't permanently degrade the service.
    """
    logger.info("MindGraphReconnectWatcher started.")
    while True:
        if not orchestrator.mindgraph.connected:
            try:
                await orchestrator.mindgraph.connect()
                await orchestrator.mindgraph.ensure_schema()
                orchestrator.runtime_health.mark_up("neo4j")
                logger.info("MindGraphReconnectWatcher: connection restored.")
            except Exception as e:
                orchestrator.runtime_health.mark_down("neo4j", "NEO4J_UNAVAILABLE")
                logger.warning(f"MindGraphReconnectWatcher: still unreachable ({e})")

        await asyncio.sleep(60)


async def dcx_reconnect_watcher(orchestrator):
    """Re-probe the DCX trinity on an interval, not once at boot.

    orchestrator.boot() calls dcx.connect() exactly once. Everything the
    Grid reports about DCX afterwards — state, present_models, checked_at —
    is served from that single snapshot, so the health card was a
    photograph wearing the clothes of a live check: a box whose Ollama had
    been reachable for hours still read UNREACHABLE / 0 of 3 pulled, with a
    checked_at frozen at process start.

    Unlike the MindGraph watcher this re-probes even while connected. A
    retry-only-when-down loop can restore a dropped link but can never
    notice one dropping, and it would leave checked_at stale for the whole
    lifetime of a healthy process.
    """
    logger.info("DCXReconnectWatcher started.")
    while True:
        was_connected = orchestrator.dcx.connected
        try:
            await orchestrator.dcx.connect()
            if orchestrator.dcx.connected:
                orchestrator.runtime_health.mark_up("ollama")
                if not was_connected:
                    logger.info(
                        "DCXReconnectWatcher: Ollama reachable again (%s of %s present).",
                        len(orchestrator.dcx.present_models),
                        len(orchestrator.dcx.expected_models),
                    )
            else:
                orchestrator.runtime_health.mark_down("ollama", "OLLAMA_UNAVAILABLE")
                if was_connected:
                    logger.warning("DCXReconnectWatcher: Ollama went unreachable.")
        except Exception as e:
            orchestrator.runtime_health.mark_down("ollama", "OLLAMA_UNAVAILABLE")
            logger.warning(f"DCXReconnectWatcher: probe failed ({e})")

        await asyncio.sleep(60)


async def control_plane_reconnect_watcher(orchestrator):
    """Retry sovereign local Postgres governance independently."""
    logger.info("ControlPlaneReconnectWatcher started.")
    attempt = 0
    while True:
        if orchestrator.probe_control_plane():
            attempt = 0
            delay = 30
        else:
            attempt += 1
            delay = min(60, 5 * (2 ** min(attempt - 1, 4)))
        await asyncio.sleep(delay)
